spring.application.name=chat-service

server.port=8002

spring.profiles.active=const

# This will be ignored by Spring Profile in the environment of deployment
spring.datasource.url=jdbc:mysql://localhost:3306/webmapia
spring.datasource.username=scott
spring.datasource.password=tiger

# For local dev environment
custom.server.base-url=http://localhost:8002

# For local client
client.origin=http://localhost:3000