package com.nsl.webmapia.common;

public enum NotificationType {
    SKILL_PUBLIC,
    SKILL_PRIVATE,
    NOTIFY_WHICH_CHARACTER_ALLOCATED,
    VOTE,
    EXECUTE_BY_VOTE,
    INVALID_VOTE,
    USER_REMOVED,
    USER_ENTERED,
    QUERY_USER,
    GAME_INFO,
    PHASE_END,
    GAME_START,
    CHARACTER_GENERATION,
    PHASE_RESULT
}
