package nsl.webmapia.game.domain.gameroom.repository;

import nsl.webmapia.game.domain.gameroom.entity.GameRoom;
import nsl.webmapia.game.global.NumberConstants;
import nsl.webmapia.game.global.dto.PageDto;
import nsl.webmapia.game.global.dto.PageWrapper;

import java.time.LocalDateTime;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentSkipListMap;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.regex.Pattern;

/**
 * The default repository registered if there doesn't exist any
 * other instance of type GameRoomRepository in Spring Bean Container.
 * The data of this repository is stored in In-Memory space.
 */
public class InMemoryGameRoomRepository implements GameRoomRepository {
    private static final int AUTO_INCREMENTED_VALUE_START_VALUE = 10000;
    private static final AtomicInteger autoIncrementedId = new AtomicInteger(AUTO_INCREMENTED_VALUE_START_VALUE);
    private static final Map<Integer, GameRoom> storeIndexedById = new ConcurrentHashMap<>();
    private static final SortedMap<LocalDateTime, GameRoom> storeIndexedByCreationTime = new ConcurrentSkipListMap<>(
            (t1, t2) -> t1.isBefore(t2)
                    ? 1
                    : t1.isAfter(t2)
                    ? -1
                    : 0
    );

    @Override
    public int save(GameRoom gameRoom) {
        int autogeneratedId = autoIncrementedId.getAndIncrement();
        gameRoom.setRoomId(autogeneratedId);
        storeIndexedById.put(autogeneratedId, gameRoom);
        if (gameRoom.getCreationTime() != null) {
            storeIndexedByCreationTime.put(gameRoom.getCreationTime(), gameRoom);
        }
        return autogeneratedId;
    }

    @Override
    public Optional<GameRoom> findById(int roomId) {
        return Optional.ofNullable(storeIndexedById.get(roomId));
    }

    @Override
    public PageWrapper<GameRoom> findAll(PageDto pageDto) {
        return findHelper(pageDto, storeIndexedByCreationTime.values().stream().toList());
    }

    @Override
    public PageWrapper<GameRoom> findByRoomName(String roomName, PageDto pageDto) {
        Pattern pattern = Pattern.compile(String.format(".*%s.*", roomName));
        List<GameRoom> filtered = storeIndexedByCreationTime.values()
                .stream()
                .filter(gameRoom -> pattern.matcher(gameRoom.getRoomName()).matches())
                .toList();
        return findHelper(pageDto, filtered);
    }

    private PageWrapper<GameRoom> findHelper(PageDto pageDto, List<GameRoom> dataPool) {
        if (pageDto.getPage() == null) {
            throw new IllegalArgumentException();
        }

        int page = Math.max(0, pageDto.getPage());
        int pageSize = pageDto.getPageSize() == null || pageDto.getPageSize() <= 0
                ? NumberConstants.DEFAULT_QUERY_PAGE_SIZE.get()
                : pageDto.getPageSize();

        List<GameRoom> result =
                findInRange((page - 1) * pageSize, page * pageSize, dataPool);
        return new PageWrapper<>(
                page,
                dataPool.size() / pageSize + (dataPool.size() % pageSize == 0 ? 0 : 1),
                dataPool.size(),
                result
        );
    }

    private List<GameRoom> findInRange(int lowerBound, int upperBound, List<GameRoom> dataPool) {
        List<GameRoom> resultList = new LinkedList<>();

        int i = 0;
        for (GameRoom data : dataPool) {
            if (i >= lowerBound && i < upperBound) {
                resultList.add(data);
            }
            i++;
        }
        return resultList;
    }

    @Override
    public boolean update(GameRoomUpdateDto dto) {
        if (dto.getRoomId() == null) {
            throw new IllegalArgumentException();
        }
        GameRoom fromStore = storeIndexedById.get(dto.getRoomId());
        if (fromStore == null) {
            return false;
        }
        if (dto.getRoomName() != null) {
            fromStore.setRoomName(dto.getRoomName());
        }
        return true;
    }

    @Override
    public boolean deleteById(int roomId) {
        boolean success = storeIndexedById.remove(roomId) != null;
        if (success) {
            for (GameRoom gameRoom : storeIndexedByCreationTime.values()) {
                if (gameRoom.getRoomId() == roomId) {
                    storeIndexedByCreationTime.remove(gameRoom.getCreationTime());
                    break;
                }
            }
        }
        return success;
    }

    /**
     * Clears all instances in this repository.
     */
    public void clear() {
        storeIndexedById.clear();
        storeIndexedByCreationTime.clear();
        autoIncrementedId.set(AUTO_INCREMENTED_VALUE_START_VALUE);
    }
}
