package nsl.webmapia.game.gameroom.repository;

import nsl.webmapia.game.gameroom.domain.GameRoom;

import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * The default repository registered if there doesn't exist any
 * other instance of type GameRoomRepository in Spring Bean Container.
 * The data of this repository is stored in In-Memory space.
 */
public class InMemoryGameRoomRepository implements GameRoomRepository {
    private static final int AUTO_INCREMENTED_VALUE_START_VALUE = 10000;
    private static final AtomicInteger autoIncrementedId = new AtomicInteger(AUTO_INCREMENTED_VALUE_START_VALUE);
    private static final Map<Integer, GameRoom> store = new ConcurrentHashMap<>();

    @Override
    public int save(GameRoom gameRoom) {
        int autogeneratedId = autoIncrementedId.getAndIncrement();
        gameRoom.setRoomId(autogeneratedId);
        store.put(autogeneratedId, gameRoom);
        return autogeneratedId;
    }

    @Override
    public Optional<GameRoom> findById(int roomId) {
        return Optional.ofNullable(store.get(roomId));
    }

    @Override
    public boolean update(GameRoomUpdateDto dto) {
        if (dto.getRoomId() == null) {
            throw new IllegalArgumentException();
        }
        GameRoom fromStore = store.get(dto.getRoomId());
        if (fromStore == null) {
            return false;
        }
        if (dto.getRoomName() != null) {
            fromStore.setRoomName(dto.getRoomName());
        }
        if (dto.getHostMember() != null) {
            fromStore.setHostMember(dto.getHostMember());
        }
        return true;
    }

    @Override
    public boolean deleteById(int roomId) {
        return store.remove(roomId) != null;
    }

    /**
     * Clears all instances in this repository.
     */
    public void clear() {
        store.clear();
        autoIncrementedId.set(AUTO_INCREMENTED_VALUE_START_VALUE);
    }
}
